name: 'Validate JSON files'
description: 'Syntax validation'
inputs:
    directory:
        description: 'Directory with json files'
        required: true
        default: '.'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args: 
        - ${{ inputs.directory }}